PREF-247 | UseCase for defaulting record key to property name
neighborhoods/PrefabFitness pull request #33
Opened 2022-01-17 17:47 UTC by jpmarcotte

Relevant snippet from `UsesDefaultInterface`

```php
public const PROP_SAME_AS_DEFAULT = 'same_as_default';
public const PROP_USES_DEFAULT = 'uses_default';
public const PROP_DIFFERENT_THAN_DEFAULT = 'something_else';
```

2022-01-17 19:09 UTC, jpmarcotte commented on UseCase72/composer.json
> +    "neighborhoods/prefab": "dev-PREF-247-7x-default-record-key-to-name"
TODO: Change to a release tag after the relevant PR is merged and released.

2022-01-19 19:38 UTC, arielallon requested changes
just a couple of minor housekeeping changes requested

2022-01-19 19:38 UTC, arielallon commented on UseCase72/README.md
> +Testing whether or not the Deprecated flag works
```suggestion
# Use Case 72
Testing fallback to property name when record_key is not specified
```

2022-01-19 19:38 UTC, arielallon commented on UseCase72/composer.json
> +  "name": "neighborhoods/prefab-fitness-use-case-51",
```suggestion
{
  "name": "neighborhoods/prefab-fitness-use-case-72",
```

2022-01-20 15:34 UTC, mucha55 approved these changes

2022-02-16 16:52 UTC, mucha55 approved these changes

2022-02-16 21:34 UTC, arielallon approved these changes

2022-02-17 15:49 UTC, merged